#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — one-time TestFlight setup for the Sotto iPhone app (ADR-0032).
# Stores four secrets in the `testflight` environment of millZach/Sotto, which
# only .github/workflows/ios-testflight.yml reads. Nothing is written to disk.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
REPO="millZach/Sotto"
BUNDLE_ID="com.millzach.sotto.ios"

# env_secret NAME — set an environment secret from stdin, never echoing it.
env_secret() {
  if gh secret set "$1" --env testflight --repo "$REPO" >/dev/null 2>&1; then
    WRITTEN_SECRET+=("$1"); printf '  %s✓ set%s %s in the testflight environment\n' "$GREEN" "$RESET" "$1"
  else
    SKIPPED+=("secret $1 (gh secret set $1 --env testflight --repo $REPO)"); warn "couldn't set $1"
  fi
}

banner "Sotto for iPhone — TestFlight setup"

if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
  warn "The GitHub CLI isn't signed in. Run 'gh auth login' first, then run this again."
  exit 1
fi

stage "Your Team ID"
say "Your Apple Developer Team ID tells the build which account signs it."
open_url "https://developer.apple.com/account#MembershipDetailsCard"
step "Sign in, then find Membership details on the account page."
step "Copy the Team ID: ten letters and numbers, such as A1B2C3D4E5."
while :; do
  ask APPLE_TEAM_ID "Paste your Team ID:"
  APPLE_TEAM_ID=$(printf '%s' "$APPLE_TEAM_ID" | tr -d '[:space:]' | tr '[:lower:]' '[:upper:]')
  [[ "$APPLE_TEAM_ID" =~ ^[A-Z0-9]{10}$ ]] && break
  warn "That doesn't look like a Team ID (ten letters and numbers). Try again."
done

stage "Register the app's ID"
say "Apple needs to know the app's bundle ID before App Store Connect can use it."
open_url "https://developer.apple.com/account/resources/identifiers/add/bundleId"
step "Choose App IDs, then Continue. Choose App, then Continue."
step "Description: Sotto for iPhone"
step "Bundle ID: choose Explicit and enter  $BUNDLE_ID"
step "Leave every capability unticked. Continue, then Register."
note "If it says the ID is already registered, that's fine: it's yours already."
pause "Press Enter when $BUNDLE_ID is registered."

stage "Create the app in App Store Connect"
say "TestFlight builds belong to an app record in App Store Connect."
open_url "https://appstoreconnect.apple.com/apps"
step "Press the + button next to Apps, then New App."
step "Platforms: iOS."
step "Name: something unique on the App Store, such as \"Sotto Remote\". The home-screen name stays Sotto."
step "Primary language: English (U.S.). Bundle ID: $BUNDLE_ID. SKU: sotto-ios."
step "User Access: Full Access. Then Create."
note "If the name is taken, add a word to it; only the store listing uses it."
pause "Press Enter when the app exists."

stage "Make an App Store Connect API key"
say "GitHub signs and uploads with this key. It needs the Admin role for Apple's cloud signing."
open_url "https://appstoreconnect.apple.com/access/integrations/api"
step "Open the Team Keys tab. If it asks you to request access first, do that (the Account Holder approves)."
step "Press Generate API Key (or +). Name: Sotto GitHub TestFlight. Access: Admin. Generate."
step "Press Download on the new key. Apple lets you download it only once."
step "Copy the Key ID from the new row, and the Issuer ID shown above the table."
while :; do
  ask KEY_ID "Paste the Key ID:"
  KEY_ID=$(printf '%s' "$KEY_ID" | tr -d '[:space:]')
  [[ "$KEY_ID" =~ ^[A-Z0-9]{10}$ ]] && break
  warn "A Key ID is ten capital letters and numbers. Try again."
done
while :; do
  ask ISSUER_ID "Paste the Issuer ID:"
  ISSUER_ID=$(printf '%s' "$ISSUER_ID" | tr -d '[:space:]' | tr '[:upper:]' '[:lower:]')
  [[ "$ISSUER_ID" =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$ ]] && break
  warn "An Issuer ID looks like 12345678-abcd-1234-abcd-123456789abc. Try again."
done
KEY_FILE="$HOME/Downloads/AuthKey_${KEY_ID}.p8"
while :; do
  if [[ -f "$KEY_FILE" ]]; then
    say "Found the key file: $KEY_FILE"
  else
    ask KEY_FILE "Path to the downloaded AuthKey_${KEY_ID}.p8 file:"
    KEY_FILE="${KEY_FILE%\"}"; KEY_FILE="${KEY_FILE#\"}"
    if [[ "$KEY_FILE" == *\* ]] && command -v cygpath >/dev/null 2>&1; then KEY_FILE=$(cygpath -u "$KEY_FILE"); fi
  fi
  if [[ -f "$KEY_FILE" ]] && grep -q "BEGIN PRIVATE KEY" "$KEY_FILE"; then break; fi
  warn "That file isn't there, or isn't an App Store Connect key. Check the path."
  KEY_FILE=""
done

stage "Save the secrets to GitHub"
say "These go into the testflight environment of $REPO, which only the TestFlight job can read."
note "Team ID $APPLE_TEAM_ID · Key ID $KEY_ID · Issuer ID $ISSUER_ID · key file $(basename "$KEY_FILE")"
if confirm "Save these four secrets now?"; then
  env_secret APP_STORE_CONNECT_KEY < "$KEY_FILE"
  printf '%s' "$KEY_ID"       | env_secret APP_STORE_CONNECT_KEY_ID
  printf '%s' "$ISSUER_ID"    | env_secret APP_STORE_CONNECT_ISSUER_ID
  printf '%s' "$APPLE_TEAM_ID" | env_secret APPLE_TEAM_ID
  say ""
  say "The testflight environment now holds:"
  gh secret list --env testflight --repo "$REPO" | sed 's/^/    /'
else
  SKIPPED+=("the four testflight secrets")
fi
pause

stage "Tidy up the key file"
say "GitHub has the key now. The copy in your Downloads folder isn't needed, and anyone"
say "who finds it could publish builds as you."
if confirm "Delete $(basename "$KEY_FILE") from this computer?"; then
  rm -f "$KEY_FILE" && say "Deleted."
else
  note "Kept. Store it somewhere safe, or delete it later."
fi
pause

finish
say "Next:"
step "Tell Claude the setup is done. It pushes the first ios-testflight tag; the build takes about half an hour."
step "Install the TestFlight app on your iPhone from the App Store."
step "When the build shows in App Store Connect under TestFlight, add yourself to an Internal Testing group."
step "Open TestFlight on the iPhone and install Sotto."
printf '\n'
